name: Deploy Club on Github Pages

permissions: write-all

on:
    workflow_dispatch:
    push:
    pull_request:

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - uses: hyoo-ru/mam_build@master2
              with:
                  token: ${{ secrets.GH_PAT }}
                  package: eve
                  modules: app

            - uses: JamesIves/github-pages-deploy-action@4.1.7
              with:
                  branch: gh-pages
                  folder: eve/app/-
